[[language]]
name = "Assembly"
patterns = ["*.asm", "*.s"]
line_comment = ";"

[[language]]
name = "AWK"
patterns = ["*.awk"]
interpreters = ["awk", "gawk", "mawk", "nawk"]
line_comment = "#"

[[language]]
name = "C"
patterns = ["*.c", "*.h"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "C#"
patterns = ["*.cs"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = false }, { open = '@"', close = '"', backslash_escapes = false }]

[[language]]
name = "C++"
patterns = ["*.cpp", "*.hpp", "*.cc", "*.hh", "*.cxx", "*.hxx"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Cap'n Proto"
patterns = ["*.capnp"]
line_comment = "#"

[[language]]
name = "Carbon"
patterns = ["*.carbon"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Clojure"
patterns = ["*.clj", "*.cljs", "*.cljc"]
line_comment = ";"

[[language]]
name = "CoffeeScript"
patterns = ["*.coffee"]
line_comment = "#"
block_comment_start = "###"
block_comment_end = "###"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]

[[language]]
name = "Common Lisp"
patterns = ["*.lisp", "*.lsp", "*.cl", "*.asd"]
line_comment = ";"
block_comment_start = "#|"
block_comment_end = "|#"

[[language]]
name = "Config"
patterns = ["*.conf"]
line_comment = "#"

[[language]]
name = "Crystal"
patterns = ["*.cr"]
line_comment = "#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "CSS"
patterns = ["*.css"]
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "D"
patterns = ["*.d"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Dart"
patterns = ["*.dart"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]

[[language]]
name = "Dockerfile"
patterns = ["*.dockerfile", "Dockerfile", "Dockerfile.*"]
line_comment = "#"

[[language]]
name = "Elixir"
patterns = ["*.ex", "*.exs"]
interpreters = ["elixir"]
line_comment = "#"
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }]

[[language]]
name = "Elm"
patterns = ["*.elm"]
line_comment = "--"
block_comment_start = "{-"
block_comment_end = "-}"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }]

[[language]]
name = "Emacs Lisp"
patterns = ["*.el"]
line_comment = ";"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Erlang"
patterns = ["*.erl", "*.hrl"]
line_comment = "%"

[[language]]
name = "F#"
patterns = ["*.fs", "*.fsi", "*.fsx"]
line_comment = "//"
block_comment_start = "(*"
block_comment_end = "*)"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = false }]

[[language]]
name = "FlatBuffers"
patterns = ["*.fbs"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Game Maker Language"
patterns = ["*.gml"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "GDScript"
patterns = ["*.gd"]
line_comment = "#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = false }]

[[language]]
name = "Gleam"
patterns = ["*.gleam"]
line_comment = "//"

[[language]]
name = "GLSL"
patterns = ["*.glsl", "*.vert", "*.frag", "*.geom", "*.comp", "*.tesc", "*.tese"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"

[[language]]
name = "Go"
patterns = ["*.go"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = "`", close = "`", backslash_escapes = false }]

[[language]]
name = "Groovy"
patterns = ["*.groovy", "*.gradle"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]

[[language]]
name = "Hare"
patterns = ["*.ha"]
line_comment = "//"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "HCL"
patterns = ["*.hcl", "*.tf"]
line_comment = "#"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "HLSL"
patterns = ["*.hlsl", "*.cg", "*.cginc"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"

[[language]]
name = "HTML"
patterns = ["*.html", "*.htm"]
block_comment_start = "<!--"
block_comment_end = "-->"

[[language]]
name = "Haskell"
patterns = ["*.hs"]
line_comment = "--"
block_comment_start = "{-"
block_comment_end = "-}"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Java"
patterns = ["*.java"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = false }]

[[language]]
name = "JavaScript"
patterns = ["*.js", "*.mjs", "*.jsx"]
interpreters = ["node", "nodejs"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = "`", close = "`", backslash_escapes = true }]

[[language]]
name = "jq"
patterns = ["*.jq"]
interpreters = ["jq"]
line_comment = "#"

[[language]]
name = "JSON"
patterns = ["*.json"]

[[language]]
name = "Julia"
patterns = ["*.jl"]
interpreters = ["julia"]
line_comment = "#"
block_comment_start = "#="
block_comment_end = "=#"
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }]
docstring_delimiters = [{ open = '"""', close = '"""', backslash_escapes = true }]

[[language]]
name = "Kotlin"
patterns = ["*.kt", "*.kts"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = false }]

[[language]]
name = "Lua"
patterns = ["*.lua"]
interpreters = ["lua"]
line_comment = "--"
block_comment_start = "--[["
block_comment_end = "]]"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Make"
patterns = ["*.mk", "*.mak", "Makefile", "GNUmakefile", "Makefile.*"]
line_comment = "#"

[[language]]
name = "Nim"
patterns = ["*.nim"]
line_comment = "#"
block_comment_start = "#["
block_comment_end = "]#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }]

[[language]]
name = "Nix"
patterns = ["*.nix"]
line_comment = "#"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "OCaml"
patterns = ["*.ml", "*.mli"]
block_comment_start = "(*"
block_comment_end = "*)"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Objective-C"
patterns = ["*.m", "*.mm"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Odin"
patterns = ["*.odin"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = "`", close = "`", backslash_escapes = false }]

[[language]]
name = "Perl"
patterns = ["*.pl", "*.pm"]
interpreters = ["perl"]
line_comment = "#"

[[language]]
name = "PHP"
patterns = ["*.php"]
interpreters = ["php"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Protobuf"
patterns = ["*.proto"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Python"
patterns = ["*.py"]
interpreters = ["python", "python2", "python3"]
line_comment = "#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]
docstring_delimiters = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]

[[language]]
name = "R"
patterns = ["*.r", "*.R"]
interpreters = ["Rscript"]
line_comment = "#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Racket"
patterns = ["*.rkt"]
interpreters = ["racket"]
line_comment = ";"
block_comment_start = "#|"
block_comment_end = "|#"

[[language]]
name = "Raku"
patterns = ["*.raku", "*.rakumod", "*.rakutest", "*.rakudoc", "*.p6", "*.pm6", "*.pl6"]
interpreters = ["perl6", "raku"]
line_comment = "#"

[[language]]
name = "Ruby"
patterns = ["*.rb", "*.gemspec", "*.rake", "Gemfile", "Rakefile"]
interpreters = ["ruby"]
line_comment = "#"

[[language]]
name = "Rust"
patterns = ["*.rs"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "Sass"
patterns = ["*.sass", "*.scss"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Scala"
patterns = ["*.scala"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = false }]

[[language]]
name = "Sed"
patterns = ["*.sed"]
interpreters = ["sed", "gsed"]
line_comment = "#"

[[language]]
name = "Scheme"
patterns = ["*.scm", "*.ss"]
line_comment = ";"
block_comment_start = "#|"
block_comment_end = "|#"

[[language]]
name = "Shell"
patterns = ["*.sh", "*.bash", "*.zsh"]
interpreters = ["sh", "bash", "dash", "zsh"]
line_comment = "#"

[[language]]
name = "SQL"
patterns = ["*.sql"]
line_comment = "--"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]

[[language]]
name = "Starlark"
patterns = ["*.star", "*.bzl", "BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel"]
line_comment = "#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]
docstring_delimiters = [{ open = '"""', close = '"""', backslash_escapes = true }, { open = "'''", close = "'''", backslash_escapes = true }]

[[language]]
name = "Swift"
patterns = ["*.swift"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
multiline_strings = [{ open = '"""', close = '"""', backslash_escapes = true }]

[[language]]
name = "Tcl"
patterns = ["*.tcl", "*.tk"]
interpreters = ["tclsh", "wish"]
line_comment = "#"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]

[[language]]
name = "TOML"
patterns = ["*.toml"]
line_comment = "#"

[[language]]
name = "TypeScript"
patterns = ["*.ts", "*.tsx"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = "`", close = "`", backslash_escapes = true }]

[[language]]
name = "Vim script"
patterns = ["*.vim", ".vimrc", "vimrc", ".gvimrc", "gvimrc"]
line_comment = '"'

[[language]]
name = "WGSL"
patterns = ["*.wgsl"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"

[[language]]
name = "XML"
patterns = ["*.xml"]
block_comment_start = "<!--"
block_comment_end = "-->"

[[language]]
name = "YAML"
patterns = ["*.yaml", "*.yml"]
line_comment = "#"

[[language]]
name = "Zig"
patterns = ["*.zig"]
line_comment = "//"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }]
