patterns = ["*.odin"]
line_comment = "//"
block_comment_start = "/*"
block_comment_end = "*/"
single_line_strings = [{ open = '"', close = '"', backslash_escapes = true }, { open = "'", close = "'", backslash_escapes = true }]
multiline_strings = [{ open = "`", close = "`", backslash_escapes = false }]
